- ros_topic_name: /camera
  gz_topic_name: /wide_camera_left
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: /HeadYaw/position
  gz_topic_name: /model/Nao/joint/HeadYaw/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /HeadPitch/position
  gz_topic_name: /model/Nao/joint/HeadPitch/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /LShoulderPitch/position
  gz_topic_name: /model/Nao/joint/LShoulderPitch/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /LShoulderRoll/position
  gz_topic_name: /model/Nao/joint/LShoulderRoll/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /LElbowYaw/position
  gz_topic_name: /model/Nao/joint/LElbowYaw/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /LElbowRoll/position
  gz_topic_name: /model/Nao/joint/LElbowRoll/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /LWristYaw/position
  gz_topic_name: /model/Nao/joint/LWristYaw/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ